version: "3.8"

networks:
  postgres_network:

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  admin:
    image: dpage/pgadmin4:latest
    container_name: postgres_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5432:80"
    depends_on:
      - db
    networks:
      - postgres_network

volumes:
  postgres_data: